export const RUNTIME_FIELD_HELP: Record<string, string> = {
  "Initial Capital": "Starting capital used for this backtest or live deployment. It affects risk sizing, equity curve, drawdown and safety checks. Example: 100,000.",
  "Capital Risk %": "Percentage of capital risked per trade when using risk-based sizing. Example: 1% of $100,000 means $1,000 risk per trade. Higher values can create large drawdowns.",
  "Position Size Mode": "Risk Based calculates position size from stop loss and risk percent. Fixed Lot uses the same lot size for every trade. Fixed Quantity is for share/unit based instruments.",
  "Fixed Lot Size": "Manual lot size used for each trade. Example: 0.02 lots. High fixed lots can create unrealistic or dangerous risk.",
  "Fixed Quantity": "Manual quantity used for each trade on non-lot based instruments. Example: 10 shares/contracts. Use with a max quantity cap for safety.",
  "Max Lot Cap": "Maximum allowed lot size. This protects from oversized trades when stop loss distance is small. Example: 0.10 lots.",
  "Max Quantity Cap": "Maximum quantity cap for non-lot based instruments. Example: 100 shares. This protects from oversized orders.",
  "RR Ratio": "Reward-to-risk ratio. Example: 1:2 means target is twice the stop loss distance. Higher RR can reduce win rate but improve payoff.",
  "SL Mode": "Defines how stop loss is calculated: Fixed Percent, ATR volatility, recent swing high/low, or strategy suggested stop. This directly affects trade risk and lot sizing.",
  "ATR Period": "Number of candles used to calculate Average True Range. Example: 14. Higher values make the volatility estimate smoother.",
  "ATR Multiplier": "Multiplier applied to ATR to calculate stop loss distance. Example: 1.5. Higher multiplier means wider stop and usually smaller position size.",
  "Swing Lookback": "Number of candles used to find recent swing high/low for stop loss placement. Example: 5 or 10 candles.",
  "Fixed Price Risk %": "Stop loss distance as a fixed percent of entry price. Example: 0.20% means SL is 0.20% away from entry. Too tight can cause noisy exits.",
  "Entry Mode": "Controls when trade enters after signal. Next Candle Open is safer for realistic backtests because it avoids entering before the candle is complete.",
  "Exit on Opposite Signal": "Closes current trade when an opposite signal appears. This can reduce losses but may exit before the original target.",
  "Allow Long": "Allows buy trades. Turn OFF to test short-only behavior or restrict a strategy.",
  "Allow Short": "Allows sell trades. Turn OFF when the market/account should only take long trades.",
  "Intraday Square Off": "For supported intraday Indian instruments, closes positions near the selected time. It is disabled for forex/metals like XAUUSD.",
  "Square Off Time": "Time used to close intraday Indian market positions. Example: 15:15. Not used for forex/metals.",
  "Max Trades Per Day": "Limits number of trades per day to avoid overtrading. Example: 3 trades/day. Leave as No Limit only for research.",
  "Max Open Positions": "Limits simultaneous open positions. Example: 1 keeps the system simple and risk controlled.",
  "Break Even Enabled": "When enabled, stop loss can move to entry after trade reaches selected profit. This can reduce losses but may exit early.",
  "Break Even Trigger R": "Profit multiple required before stop loss moves to entry. Example: 1R means profit equals initial risk.",
  "Trailing Stop Enabled": "When enabled, stop loss can follow price after trade moves in profit. This can protect gains but may cut winners early.",
  "Trailing Mode": "Method used to trail stop. ATR trail uses volatility; swing/EMA trail follows structure or moving average behavior.",
  "Trail Start R": "Profit multiple after which trailing starts. Example: 1.5R means trailing begins after profit reaches 1.5 times initial risk.",
  "Trail ATR Multiplier": "ATR multiplier used for trailing stop distance. Higher values trail wider and may give trades more room.",
  "Partial Exit Enabled": "Closes part of the position at selected profit level. This can lock in gains but reduces the size left for final target.",
  "Partial Exit At R": "R multiple where partial exit happens. Example: 1R closes part when profit equals initial risk.",
  "Partial Exit Percent": "Percent of position closed during partial exit. Example: 50% closes half and lets the remaining position continue.",
};

export const STRATEGY_PARAM_HELP = "Strategy-specific parameter. Changing this may affect signal frequency and trade quality. Example: a larger period usually creates fewer but smoother signals.";
