'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { ArrowRight, Brain, TrendingUp, Shield, Zap, Users, BarChart3, Rocket } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { GlassCard } from '@/components/ui/GlassCard';

export default function LandingPage() {
  const router = useRouter();

  const handleGetStarted = () => {
    router.push('/auth/signup');
  };

  const handleSignIn = () => {
    router.push('/auth/login');
  };

  const features = [
    {
      icon: <Brain className="w-8 h-8 text-purple-400" />,
      title: "AI Strategy Builder",
      description: "Create sophisticated trading strategies powered by machine learning algorithms"
    },
    {
      icon: <TrendingUp className="w-8 h-8 text-green-400" />,
      title: "Backtest Engine",
      description: "Test your strategies against historical data with advanced performance metrics"
    },
    {
      icon: <Zap className="w-8 h-8 text-yellow-400" />,
      title: "AI Signals",
      description: "Receive real-time trading signals generated by our advanced AI models"
    },
    {
      icon: <Shield className="w-8 h-8 text-blue-400" />,
      title: "Broker Integrations",
      description: "Seamlessly connect with multiple brokers for automated trade execution"
    },
    {
      icon: <BarChart3 className="w-8 h-8 text-pink-400" />,
      title: "Advanced Analytics",
      description: "Deep insights and comprehensive reports to optimize your trading performance"
    },
    {
      icon: <Users className="w-8 h-8 text-cyan-400" />,
      title: "Community Insights",
      description: "Learn from successful strategies and collaborate with other traders"
    }
  ];

  const stats = [
    { label: "Active Users", value: "10K+" },
    { label: "Strategies", value: "500+" },
    { label: "Backtests", value: "100K+" },
    { label: "Brokers", value: "15+" }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      {/* Navigation Bar */}
      <nav className="fixed top-0 w-full bg-black/20 backdrop-blur-md border-b border-white/10 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-4">
              <div className="w-10 h-10 bg-gradient-to-br from-purple-400 to-pink-400 rounded-lg flex items-center justify-center">
                <Rocket className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold text-white">AlgoAgentX</span>
            </div>
            <div className="hidden md:flex space-x-8 text-sm text-gray-300">
              <a href="#features" className="hover:text-white transition-colors">Features</a>
              <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
              <a href="#support" className="hover:text-white transition-colors">Support</a>
            </div>
            <div className="flex space-x-4">
              <Button
                variant="ghost"
                onClick={handleSignIn}
                className="text-white border border-white/20 hover:bg-white/10"
              >
                Sign In
              </Button>
              <Button
                onClick={handleGetStarted}
                className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white font-semibold"
              >
                Get Started
                <ArrowRight className="ml-2 w-4 h-4" />
              </Button>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <main className="pt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="text-center">
            <h1 className="text-5xl md:text-7xl font-bold text-white mb-6">
              Scale Up Your
              <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent"> AI Trading</span>
            </h1>
            <p className="text-xl md:text-2xl text-gray-300 mb-12 max-w-3xl mx-auto leading-relaxed">
              Empower your trading journey with cutting-edge AI algorithms, 
              sophisticated backtesting, and real-time market insights. 
              Join thousands of traders who trust AlgoAgentX for their investment decisions.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Button
                onClick={handleGetStarted}
                size="lg"
                className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white text-lg font-semibold px-8 py-6 rounded-full shadow-2xl hover:shadow-purple-500/25 transition-all duration-300 transform hover:scale-105"
              >
                Start Trading Now
                <ArrowRight className="ml-3 w-5 h-5" />
              </Button>
              <Button
                variant="outline"
                onClick={handleSignIn}
                size="lg"
                className="border-2 border-white/30 text-white hover:bg-white/10 text-lg font-semibold px-8 py-6 rounded-full transition-all duration-300 hover:border-white/50 hover:scale-105"
              >
                Sign In to Continue
              </Button>
            </div>
          </div>
        </div>

        {/* Stats Section */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {stats.map((stat, index) => (
              <div key={index} className="glass-card p-6">
                <div className="text-3xl font-bold text-white mb-2">{stat.value}</div>
                <div className="text-gray-400 text-sm">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Features Section */}
        <div id="features" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">Powerful Features</h2>
            <p className="text-gray-300 text-lg">Everything you need to succeed in algorithmic trading</p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <GlassCard key={index} className="p-8 hover:shadow-purple-500/20">
                <div className="flex flex-col space-y-4">
                  <div className="w-16 h-16 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full flex items-center justify-center">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-semibold text-white">{feature.title}</h3>
                  <p className="text-gray-400 leading-relaxed">{feature.description}</p>
                </div>
              </GlassCard>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20 text-center">
          <GlassCard className="p-12">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              Ready to Transform Your Trading?
            </h2>
            <p className="text-gray-300 text-lg mb-8 leading-relaxed">
              Join thousands of traders who have already discovered the power of AI-driven trading. 
              Start with our free plan and upgrade as you grow.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Button
                onClick={handleGetStarted}
                size="lg"
                className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white text-lg font-semibold px-8 py-6 rounded-full shadow-2xl hover:shadow-purple-500/25 transition-all duration-300 transform hover:scale-105"
              >
                Get Started Free
                <ArrowRight className="ml-3 w-5 h-5" />
              </Button>
              <Button
                variant="outline"
                onClick={handleSignIn}
                size="lg"
                className="border-2 border-white/30 text-white hover:bg-white/10 text-lg font-semibold px-8 py-6 rounded-full transition-all duration-300 hover:border-white/50 hover:scale-105"
              >
                Already have an account? Sign In
              </Button>
            </div>
          </GlassCard>
        </div>
      </main>
    </div>
  );
}